version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
