version: "3.8"

services:
  web:
    build: .
    container_name: django_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - web
      - redis

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'django-app-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

  redis:
    image: "redis:alpine"

#volumes:
#  mysql_data:
