# Generated by Django 5.1.5 on 2025-03-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapeddata_price_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='update_frequency',
            field=models.IntegerField(default=6, help_text='Update interval in hours'),
        ),
    ]
