# Generated by Django 5.1.7 on 2025-03-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scrapeddata_update_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
