# Generated by Django 5.1.7 on 2025-03-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_scrapeddata_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='update_frequency',
            field=models.CharField(choices=[('minutes', 'Every Few Minutes'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], default='hourly', help_text='How often the product should be updated', max_length=10),
        ),
    ]
