# Generated by Django 5.1.9 on 2025-05-09 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_competitor_product_tenant_competitorproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerecommendation',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_price_recommendation', to='scraper.tenant'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules_product', to='scraper.product'),
        ),
        migrations.AlterField(
            model_name='pricerecommendation',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pricerecommendation',
            name='recommended_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
