# Generated by Django 5.1.9 on 2025-05-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_pricerecommendation_tenant_pricingrule_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerecommendation',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='pricerecommendation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='competitorproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pricerecommendation',
            name='calculated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pricerecommendation',
            name='competitor_data_used',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='target_margin',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='competitorproduct',
            name='current_price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='competitorproduct',
            name='previous_price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pricerecommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.product'),
        ),
        migrations.AlterField(
            model_name='pricerecommendation',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pricerecommendation',
            name='recommended_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='PricingRule',
        ),
    ]
